package nl.hu.inno.humc.monoliet.domain.middel;

public enum TypeGevaar {
    GIFTIG,
    ZEERGIFTIG,
    BIJTEND,
    SCHADELIJK,
    IRRITEREND,
    OXIDEREND,
    REDUCINGAGENT,
    VOORZELFONTBRANDINGVATBAAR,
    ONTVLAMBAAR,
    ONTPLOFBAAR,
    CARCINOGEEN,
    SCHADELIJKVOORHETMILIEU,
    GEVAARLIJKINCONTACTMETWATER,
    RADIOACTIEF

}
